### ISSUE TITLE
Configure a culture invariant sort option

### ISSUE THREAD

**Issue by jtaherkhani** [stefanegli/ResxFormatter#2]
Steps to recreate:
![image](https://user-images.githubusercontent.com/64000675/112979881-740c1d80-9159-11eb-913a-a03235f54eb4.png)

1) Set machine localization to US English ->
(Control Panel -> Clock and region -> Formats -> English (United States)

1) Create an en-us resx file with the following labels:
"Api"
"Assigned"
"Attribute"
"Average"
"Azure"

2) See the resx be sorted to the above alphabetical order.

3) Update machine localization from En-Us over to Estonian
(Control Panel -> Clock and Region -> Formats -> Estonian (Estonia))

4) Open Visual Studio > Navigate to the Resx file

5) Create a new label + hit save.

6) The order is updated to:

"Api"
"Assigned"
"Azure"
"Attribute"
"Average"

**Why**
According to the Estonian alphabet [Z comes before T](https://en.wikipedia.org/wiki/Estonian_orthography#:~:text=The%20official%20Estonian%20alphabet%20has,loanwords%20and%20foreign%20proper%20names.) So it alphabetizes based on the local machine rules for the user as opposed to the resx language of choice.

 
**Potential Solution**
Add an option on sorting to allow culture invariant sorting, so all resx will follow the same pattern independent of if the team is across different localizations.

**Comment by stefanegli** [comment]
Thanks for reporting this problem and also for providing such an excellent description of it.

I think that I rather not add an option to control the sort order since the goal of this extension is to normalize files. Adding an option would potentially create problems like the one you observed because a team member use the wrong sort options. 

I fixed the problem by using "ordinal comparison". A preview of this can be downloaded here:
https://www.vsixgallery.com/extension/ResxFormatter.61507132-4401-47b1-9950-575e43b964c6

I hope this solution is acceptable to you (and all other users) of my extension :-)

**Comment by jtaherkhani** [comment]
That works for us!

Thanks for the quick turn around, I'll go ahead and close this.
