### ISSUE TITLE
Status of ResxFormatter for VS2022?

### ISSUE THREAD

**Issue by OhSoGood** [stefanegli/ResxFormatter#5]
Hi Stefan

Thank you very much for ResXFormatter, it's a simple but so useful tool notably when using git. I saw there is a preview version for VS2022, as of August 2021. What's the status for it? Is it stable, does it has bugs, would you have a release date in mind?

Thank again for your time and effort on it!

**Comment by stefanegli** [comment]
Thanks for your kind feedback :-)

I think the preview version does not have very serious problems. It does suffer from the bug described in #4 but as a workaround you can use another reload setting. I did not yet release the new version because I expected that I can somehow upload two packages (one for 2017/2019 and one for 2022) but this does not seem to be the case. Some other plugins simply created a new marketplace listing and some seem to have figured out to create one package to rule them all ;-)

Please feel free to try the preview version. If something "really" does not work, then I will try to fix it.

regards
stefan

**Comment by stefanegli** [comment]
Instead of download the preview version from here, you could download the latest build from the VSIX gallery:
https://www.vsixgallery.com/extension/ResxFormatter.61507132-4401-47b1-9950-575e43b964c6/

DISCLAIMER: I do not control this website, but it seems trustworthy enough and I also use the builds from there (whenever I push an appveyor build is triggered and the result is uploaded there)
