### ISSUE TITLE
Disable generation of resx files

### ISSUE THREAD

**Issue by LaraSQP** [stefanegli/ResxFormatter#8]
First, thank you very, very much for this extension. It's a must have.

As you know, most of the context of a resx file is clutter, in fact, most of the time, the entire file is useless.

Would it be possible to add an option to automatically delete empty resx files or, better yet, disable their generation?

Thanks again.

**Comment by stefanegli** [comment]
I am glad that you like the extension.

I think if someone deletes the last entry in a resx file, then it is up to this person if the file is deleted or not. It would be too surprising if a file just gets deleted: Imaging you edit a word document and the entire file just disappears just because you clear the contents of the file.

I am not sure what you mean by "disable their generation": I am not aware of mechanisms that automatically create resx files that the user did not ask for. Thus I am not really sure  what my extension should do...

**Comment by LaraSQP** [comment]
The quick reply is appreciated.

I suppose that, after determining the `resx` file is empty, its deletion would also imply updating the `csproj` file, which would be messy.

I guess I'm left with manual deletion.

Thanks again.
